name: Update Version and Merge

on:
  pull_request:
    types: [closed]

jobs:
  update-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR labels
        id: get_labels
        run: |
          pr_number=${{ github.event.pull_request.number }}
          labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/labels" | jq -r '.[].name')
          echo "labels=$labels" >> $GITHUB_ENV

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Setup Node.js (needed for the script)
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Update version number for hotfix
        if: contains(env.labels, 'hotfix')
        id: update_version_hotfix
        run: |
          file="wp-content/themes/georgetown/src/GeorgetownSite.php"
          version_line=$(grep -n "\$theme_version = '" $file | cut -d: -f1)
          version=$(grep "\$theme_version = '" $file | sed -E "s/.*theme_version = '([0-9]+\.[0-9]+\.[0-9]+)'.*/\1/")
          IFS='.' read -r -a version_parts <<< "$version"
          new_patch_version=$(printf "%02d" $((version_parts[2] + 1)))
          new_version="${version_parts[0]}.${version_parts[1]}.${new_patch_version}"
          sed -i "${version_line}s/.*/  protected \$theme_version = '${new_version}';/" $file
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add $file
          git commit -m "Increment version to ${new_version}"

      - name: Update version number for feature
        if: contains(env.labels, 'feature')
        id: update_version_feature
        run: |
          file="wp-content/themes/georgetown/src/GeorgetownSite.php"
          version_line=$(grep -n "\$theme_version = '" $file | cut -d: -f1)            
          version=$(grep "\$theme_version = '" $file | sed -E "s/.*theme_version = '([0-9]+\.[0-9]+\.[0-9]+)'.*/\1/")
          IFS='.' read -r -a version_parts <<< "$version"
          new_minor_version=$(printf "%02d" $((version_parts[1] + 1)))
          new_version="${version_parts[0]}.${new_minor_version}.${version_parts[2]}"
          sed -i "${version_line}s/.*/  protected \$theme_version = '${new_version}';/" $file
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add $file
          git commit -m "Increment version to ${new_version}"
        
      - name: Push changes to main
        run: |
          git push git@github.com:${{ github.repository }}.git main

      - name: Fetch all branches
        run: git fetch origin

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: Merge main into develop
        run: |
          git merge origin/main

      - name: Push changes to develop
        run: |
          git push git@github.com:${{ github.repository }}.git develop
