name: Update PR Description

on:
    pull_request:

jobs:
    update-pr-description:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Extract branch name and ID
              id: extract
              run: |
                BRANCH_NAME=${{ github.head_ref }}
                echo "Branch name: $BRANCH_NAME"
                TASK_ID=$(echo $BRANCH_NAME | grep -oP '(?<=-)\d+$' || echo "")
                echo "Extracted Task ID: $TASK_ID"
                echo "task_id=$TASK_ID" >> $GITHUB_OUTPUT

            - name: Update PR Description
              uses: nefrob/pr-description@v1.1.2
              with:
                content: |
                  ${{ steps.extract.outputs.task_id != '' && '## Wrike Link\nhttps://www.wrike.com/open.htm?id=${{ steps.extract.outputs.task_id }}\n' || '## Wrike Link\nhttps://www.wrike.com/open.htm?id=TASKID_GOES_HERE\n' }}
    
                    ## Multidev Link
                    https://pr-${{ github.event.number }}-guoa-wordpress-multisite.pantheonsite.io                    
                regex: "<!-- start match -->.*?<!-- end match -->"
                regexFlags: ims
                token: ${{ secrets.GITHUB_TOKEN }}